### ISSUE TITLE
tahm class isn't a singleton

### ISSUE THREAD

**Issue by tamtaasatiani** [tamtaasatiani/tahmlib#2]
There should only be one instance of the engine and literal game, but the tahm class isn't a singleton. Switching it to singleton makes more sense

**Comment by iyakushev** [comment]
Hello, Tamta! Nice project. I believe you could make it better without relying on singletons. Also I should note that your current singleton implementation is not thread-safe.
For small projects it's completely ok to bundle both game and engine together as a single executable. However, if you wish to make it reusable you have to split them into two separate entities. Dynamically or statically linking the engine to the game code. Never worked with VCProj (CMake fanboi), so I won't be of much help here, but I'm sure you can easily google that. The main loop could be incapsulated into the engine's API or left for implementation in the user's code. This allows the game to be a main point of execution while the engine provides API for subsystems and manages resources.
Your engine API could remain the same. Though I would suggest you to add namespaces engine wide to avoid unnecessary collisions with users code. 
```cpp
// engine.h
namespace TahmEngine
{
void start();
void update();
void draw();
void keyPressed(const Event& event);  // <-- Judging by the docs event union is aligned to at least 8 bytes. Better take it by ref to avoid copying large structs on the stack.
};

// ----------------
// user's main.cpp (+linking with TahmEngine)
void TahmEngine::start()  // <-- tempted to move those into Tahm class
{
    // logic goes here
}

int main() 
{
    auto engine = TahmEngine::Tahm();
    engine.init();
    engine.doMainLoop();
    return 0;
}
``` 
And one small suggestion: you can use `std::make_unique<T>(...)` instead of `new`. This will ease your life by automatically destructing owned objects (meaning you could use defaulted destructors) while producing zero overhead in most cases.
Sorry for dumping all of that into an issue, didn't find discussion panel in the project.
